        ; 01
        dg --------
        dg --------
        dg --------
        dg --------
        dg --------
        dg --------
        dg --------
        dg --------

        ; 02
        dg --------
        dg --------
        dg --------
        dg --------
        dg --------
        dg -XXX-X--
        dg XXXXX-X-
        dg XXXXX-X-

        ; 03
        dg --------
        dg --------
        dg --------
        dg --------
        dg --------
        dg ------X-
        dg ------X-
        dg ------X-

        ; 04
        dg -XXX-X--
        dg --X-X---
        dg -XXX-X--
        dg -XXX-X--
        dg -XXX-X--
        dg --X-X---
        dg -XXX-X--
        dg -XXX-X--

        ; 05
        dg --------
        dg --------
        dg --------
        dg --------
        dg --------
        dg X-------
        dg X-------
        dg X-------

        ; 06
        dg ------X-
        dg ------X-
        dg ------X-
        dg ------X-
        dg ------XX
        dg ------XX
        dg -------X
        dg -----X--

        ; 07
        dg -XXX-X--
        dg --X-X---
        dg -XXX-X--
        dg -XXX-X--
        dg -XXX-X-X
        dg X-XXX-XX
        dg XXXX-XXX
        dg XXXX-XX-

        ; 08
        dg X-------
        dg X-------
        dg X-------
        dg X-------
        dg X-------
        dg X-------
        dg --------
        dg -X------

        ; 09
        dg -----XX-
        dg ------XX
        dg ------X-
        dg -------X
        dg --------
        dg ------XX
        dg -----XXX
        dg -----XX-

        ; 0a
        dg -XXX-X--
        dg X-X-X-XX
        dg -XXX-X--
        dg XXXX-XXX
        dg --XXX---
        dg XXXXXXXX
        dg XXXXXXXX
        dg --------

        ; 0b
        dg XX------
        dg X-------
        dg X-------
        dg --------
        dg --------
        dg X-------
        dg XX------
        dg XX------

        ; 0c
        dg -----X--
        dg -----X--
        dg -----X--
        dg -----X--
        dg -----X--
        dg -----X--
        dg -----X--
        dg -------X

        ; 0d
        dg -XXXXX--
        dg -XXXXX--
        dg -XXXXX--
        dg XXXXXXX-
        dg XXXXXXX-
        dg XXXXXXX-
        dg XXXXXXX-
        dg XXXXXXXX

        ; 0e
        dg -X------
        dg -X------
        dg -X------
        dg -X------
        dg -X------
        dg -X------
        dg -X------
        dg --------

        ; 0f
        dg -------X
        dg ------XX
        dg -----XXX
        dg ---XXXXX
        dg -----XXX
        dg ------XX
        dg -------X
        dg -------X

        ; 10
        dg XXXXXXXX
        dg XXXXXXXX
        dg XXXXXXXX
        dg XXXXXXXX
        dg XXXXXXXX
        dg XXXXXXXX
        dg XXXXXXXX
        dg XXXXXXXX

        ; 11
        dg --------
        dg X-------
        dg XX------
        dg XXXX----
        dg XX------
        dg X-------
        dg --------
        dg --------

        ; 12
        dg XXXXXXX-
        dg XXXXXXX-
        dg XXXXXXX-
        dg XXXXXXX-
        dg XXXXXXX-
        dg XXXXXXX-
        dg XXXXXXX-
        dg XXXXXXX-

        ; 13
        dg --------
        dg -------X
        dg -------X
        dg ------XX
        dg -----XXX
        dg ----XXXX
        dg -XXXXXXX
        dg ----XXXX

        ; 14
        dg XXXXXXX-
        dg XXXXXXXX
        dg XXXXXXXX
        dg XXXXXXXX
        dg XXXXXXXX
        dg XXXXXXXX
        dg XXXXXXXX
        dg XXXXXXXX

        ; 15
        dg --------
        dg --------
        dg --------
        dg X-------
        dg XX------
        dg XXX-----
        dg XXXXXX--
        dg XXX-----

        ; 16
        dg -----XXX
        dg ------XX
        dg -------X
        dg -------X
        dg --------
        dg --------
        dg --------
        dg --------

        ; 17
        dg XXXXXXXX
        dg XXXXXXXX
        dg XXXXXXXX
        dg XXXXXXXX
        dg XXXXXXX-
        dg XXXXXXX-
        dg -XXXXX--
        dg -XXXXX--

        ; 18
        dg XX------
        dg X-------
        dg --------
        dg --------
        dg --------
        dg --------
        dg --------
        dg --------

        ; 19
        dg -XXXXX--
        dg -XXXXX--
        dg -XXXXX--
        dg --XXX---
        dg --XXX---
        dg --XXX---
        dg --XXX---
        dg ---X----

        ; 1a
        dg ---X----
        dg ---X----
        dg ---X----
        dg ---X----
        dg ---X----
        dg ---X----
        dg ---X----
        dg --------

        ; 1b
        dg -XX--X--
        dg --X-X---
        dg -XXX-X--
        dg -XXX-X--
        dg -XXX-X--
        dg --X-X---
        dg -XXX-X--
        dg -X-X-X--

        ; 1c
        dg -XX--X--
        dg --X-X---
        dg -XXX-X--
        dg -XXX-X--
        dg -XXX-X-X
        dg X-XXX-XX
        dg XXXX-XXX
        dg XXXX--X-

        ; 1d
        dg -XX--X--
        dg X-X---XX
        dg -XXX-X--
        dg XXXX-XXX
        dg --XXX---
        dg XXXXXXXX
        dg XXXXXXXX
        dg --------

        ; 1e
        dg -----X--
        dg -----X--
        dg -----X--
        dg -----X--
        dg -----X--
        dg -----X--
        dg -----X--
        dg --------

        ; 1f
        dg -XXXXX--
        dg -XXXXX--
        dg -XXXXX--
        dg --XXXX--
        dg -X-XXX--
        dg -XXXXX--
        dg -XX-XX--
        dg -XXX-X--

        ; 20
        dg --------
        dg --------
        dg --------
        dg --------
        dg ------X-
        dg --------
        dg --------
        dg --------

        ; 21
        dg -XXXX---
        dg -XXX-X--
        dg -XXX-X--
        dg -XXXXX--
        dg --XXXX--
        dg -XXXXX--
        dg -XXXXX--
        dg -XXXXX--

        ; 22
        dg --------
        dg --------
        dg --------
        dg --------
        dg --------
        dg --XXX---
        dg ---XX---
        dg ----X---

        ; 23
        dg -X------
        dg -XX-----
        dg -XX-----
        dg -XXX--X-
        dg -XXX----
        dg -XXXX---
        dg -XXXX---
        dg -XX-----

        ; 24
        dg -XXXXX--
        dg --XXXX--
        dg ---XX---
        dg --------
        dg X------X
        dg --------
        dg --------
        dg --------

        ; 25
        dg --------
        dg --------
        dg --------
        dg X-------
        dg X---X---
        dg X-------
        dg X-------
        dg --------

        ; 26
        dg -XX-----
        dg -X------
        dg --------
        dg --------
        dg --------
        dg -----X--
        dg --------
        dg --------

        ; 27
        dg ------X-
        dg ------X-
        dg -----X--
        dg -----XX-
        dg ----XXX-
        dg ---XXXX-
        dg ----XXX-
        dg -----XX-

        ; 28
        dg --------
        dg --------
        dg --------
        dg --------
        dg --------
        dg --X-----
        dg --------
        dg --------

        ; 29
        dg --------
        dg ---X----
        dg ---XX---
        dg ---XXX--
        dg --------
        dg --------
        dg --------
        dg --------

        ; 2a
        dg -X---XX-
        dg -XX---X-
        dg -XX-----
        dg -XXX----
        dg -XXXX---
        dg -XXXXX--
        dg -XXXXX--
        dg -XXXXX--

        ; 2b
        dg --------
        dg --X-----
        dg ---X----
        dg --------
        dg --------
        dg --------
        dg --------
        dg --------

        ; 2c
        dg --X-----
        dg --XX----
        dg --XX----
        dg --X-----
        dg --------
        dg --------
        dg --------
        dg --------

        ; 2d
        dg --XXXX--
        dg ---X----
        dg --------
        dg --------
        dg --------
        dg --X-----
        dg -XX-----
        dg -XXX----

        ; 2e
        dg --------
        dg ----XX--
        dg ----XX--
        dg ---XXX--
        dg ----XX--
        dg ----XX--
        dg -----X--
        dg --------

        ; 2f
        dg -XXXX---
        dg -XXXXX--
        dg -XXXXX--
        dg -XXXXX--
        dg -XXXXX--
        dg -XXXXX--
        dg --XXX---
        dg --XXX---

        ; 30
        dg --XXX---
        dg ---X----
        dg ---X----
        dg --------
        dg --------
        dg --------
        dg --------
        dg --------

        ; 31
        dg XXXXXXXX
        dg XXXXXXXX
        dg XXXXXXXX
        dg XXXXXXXX
        dg -XXX-XXX
        dg XXXXXXXX
        dg -X-X-X-X
        dg XXXXXXXX

        ; 32
        dg XXXXXXXX
        dg XXXXXXXX
        dg XXXXXXXX
        dg XXXXXXXX
        dg XXXXXXXX
        dg XXXXXXXX
        dg XXX-XXXX
        dg XXXXXXXX

        ; 33
        dg XXXXXXXX
        dg XXXXXXXX
        dg XXXXXXXX
        dg XXXXXXXX
        dg XXXXXXXX
        dg XXXXXXXX
        dg XXXXXX-X
        dg XXXXXXXX

        ; 34
        dg XXXXXXXX
        dg XXXXXXXX
        dg XXXXXXXX
        dg XXXXXXXX
        dg XXXX-X-X
        dg XXXXXXXX
        dg --------
        dg -XXXXXX-

        ; 35
        dg XXXXXXXX
        dg XXXXXXXX
        dg XX-X---X
        dg XXX-XX--
        dg -X-X-X-X
        dg XXXXXXXX
        dg -------X
        dg --------

        ; 36
        dg XXXXXXXX
        dg XXXXXXXX
        dg -X-XXXXX
        dg -XXXXX-X
        dg ---X-X-X
        dg X-------
        dg -X------
        dg --------

        ; 37
        dg XXXXXXXX
        dg XXXXXXXX
        dg XXXX----
        dg XXX--XXX
        dg -X---X--
        dg X------X
        dg -----X-X
        dg --------

        ; 38
        dg XXXXXXXX
        dg XXXXXXXX
        dg -XXXXXXX
        dg XXXXXXXX
        dg -X-X-XXX
        dg XXXXXXXX
        dg -X-X-X-X
        dg -------X

        ; 39
        dg XXXXXXXX
        dg XXXXXXXX
        dg XXXXXXXX
        dg XXXXXXXX
        dg XXXX-X-X
        dg XXXXXXXX
        dg -X-X-X-X
        dg X-X-X-X-

        ; 3a
        dg XXXXXXXX
        dg XXXXXXXX
        dg XXXX-X-X
        dg XXXXXXXX
        dg -X-X-X-X
        dg XXXXX-X-
        dg -X-X-X-X
        dg X-X-X-XX

        ; 3b
        dg XX-X-X-X
        dg XXXXXXXX
        dg -X-X-X-X
        dg XXXXXXXX
        dg -X-X-X-X
        dg X-XXX-XX
        dg -X-X-X-X
        dg XXXXXXXX

        ; 3c
        dg XX-XXXXX
        dg XXXXXXXX
        dg -X-X-X-X
        dg XXXXXXXX
        dg -X-X-X-X
        dg XXXXXXXX
        dg -X-X-X-X
        dg XXXXXXXX

        ; 3d
        dg XXXXXXXX
        dg XXXXXXXX
        dg -XXXXXXX
        dg XXXXXXXX
        dg -X-X-X-X
        dg XXXXXXXX
        dg -X-X-XXX
        dg XXXXXXXX

        ; 3e
        dg XXXXXXXX
        dg XXXXXXXX
        dg XXXXXXXX
        dg XXXXXXXX
        dg -X-XXXX-
        dg XXXXXXXX
        dg -XXXXXXX
        dg XXXXXXXX

        ; 3f
        dg XXXXXXXX
        dg XXXXXXXX
        dg XXXXXXXX
        dg XXXXXXXX
        dg XXXXX-XX
        dg XXXXXXXX
        dg XXXXXXXX
        dg XXXXXXXX

        ; 40
        dg -X-X-X-X
        dg XXXXXXXX
        dg -X-X-X-X
        dg XXX-XXXX
        dg -X-X-X-X
        dg X-X-X-XX
        dg -X-X-X-X
        dg XXXXXXX-

        ; 41
        dg -X-X-XXX
        dg XXXXXXXX
        dg -X-X-X-X
        dg XXXXXXXX
        dg -X-XX---
        dg X-XX--X-
        dg -X-X-X-X
        dg X-X-X-X-

        ; 42
        dg XXXXXXXX
        dg XXXXXXXX
        dg -X-X-X-X
        dg X-------
        dg ---X----
        dg XXX-----
        dg ----XX--
        dg X-------

        ; 43
        dg XX-X-X-X
        dg XXXXXXXX
        dg --------
        dg --------
        dg --------
        dg --------
        dg --------
        dg --------

        ; 44
        dg -X-X-X-X
        dg XXXX----
        dg --------
        dg --------
        dg --------
        dg --------
        dg --------
        dg --------

        ; 45
        dg -X-X----
        dg --------
        dg --------
        dg --------
        dg --------
        dg --------
        dg --------
        dg --------

        ; 46
        dg -------X
        dg --------
        dg --------
        dg --------
        dg --------
        dg --------
        dg --------
        dg --------

        ; 47
        dg -X-X-X--
        dg ---XXXXX
        dg -------X
        dg --------
        dg -----X-X
        dg -------X
        dg --------
        dg --------

        ; 48
        dg -X-X-X-X
        dg X-XXXXXX
        dg -X-X-X-X
        dg -XXXXXXX
        dg ---XXX-X
        dg XXXXXXXX
        dg -XXXXXXX
        dg --XXXXXX

        ; 49
        dg -X-X-X-X
        dg XXXXXXXX
        dg -X-X-X-X
        dg XXXXXXXX
        dg XXXXXXXX
        dg XXXXXXXX
        dg XXXXXXXX
        dg XXXXXXXX

        ; 4a
        dg -X-X-X-X
        dg XXXXXXXX
        dg -XXX-XXX
        dg XXXXXXXX
        dg XXXXXXXX
        dg XXXXXXXX
        dg XXXXXXXX
        dg XXXXXXXX

        ; 4b
        dg -X-X-X-X
        dg XXXXXXXX
        dg XXXXXXXX
        dg XXXXXXXX
        dg XXXXXXXX
        dg XXXXXXXX
        dg XXXXXXXX
        dg XXXXXXXX

        ; 4c
        dg XX-XXXXX
        dg XXXXXXXX
        dg XXXXXXXX
        dg XXXXXXXX
        dg XXXXXXXX
        dg XXXXXXXX
        dg XXXXXXXX
        dg XXXXXXXX

        ; 4d
        dg -X-X-X-X
        dg XXXXXXXX
        dg -X-X-X--
        dg XXXX---X
        dg -X-X-X-X
        dg XXXXXXXX
        dg XX-XXXXX
        dg XXXXXXXX

        ; 4e
        dg -X-X----
        dg --------
        dg -----X-X
        dg XXXXXXXX
        dg -X-X-X-X
        dg XXXXXX--
        dg XXXX----
        dg XXXX----

        ; 4f
        dg --------
        dg --------
        dg -X-X----
        dg XX------
        dg --------
        dg --------
        dg --------
        dg X-------

        ; 50
        dg ---XXXXX
        dg -----XXX
        dg -------X
        dg -------X
        dg --------
        dg --------
        dg --------
        dg --------

        ; 51
        dg XXXXXXXX
        dg XXXXXXXX
        dg XXXXXXXX
        dg XXXXXXXX
        dg -XXXXXXX
        dg -XXXXXXX
        dg -X-X-X-X
        dg --XXXXXX

        ; 52
        dg XXXXXXXX
        dg XXXXXXXX
        dg XXXXXXXX
        dg XXXXXXXX
        dg XXXXXXXX
        dg XXXXXXXX
        dg -XXXX-XX
        dg XXXXXXXX

        ; 53
        dg XXXXXXXX
        dg XXXXXXXX
        dg XXXXXXXX
        dg XXXXXXXX
        dg XXXXXXXX
        dg XXXXXXXX
        dg X-XXXX-X
        dg XXXXXXXX

        ; 54
        dg XXXXXXXX
        dg XXXXXXXX
        dg XXXXXXXX
        dg XXXXXXXX
        dg XXXXXX-X
        dg XXXXXXXX
        dg -X-X-X-X
        dg XXXXXXXX

        ; 55
        dg XXXXXXXX
        dg XXXXXXXX
        dg XXXX-XXX
        dg XXXXXXXX
        dg -X-X-X-X
        dg XXXXXXX-
        dg -X-X----
        dg XXX-----

        ; 56
        dg XX---X-X
        dg X--XXX--
        dg -X-X----
        dg XX------
        dg --------
        dg --------
        dg --X---X-
        dg X---XX--

        ; 57
        dg --------
        dg --------
        dg --------
        dg --------
        dg --------
        dg ------XX
        dg -----X--
        dg ----X---

        ; 58
        dg --------
        dg --------
        dg --------
        dg --------
        dg XX------
        dg --X-----
        dg --X----X
        dg --X----X

        ; 59
        dg --------
        dg --------
        dg -X------
        dg -XXXXX--
        dg X----X--
        dg X----X--
        dg ----X---
        dg ----X---

        ; 5a
        dg --------
        dg --------
        dg --------
        dg --------
        dg -X------
        dg -X------
        dg XX------
        dg XX------

        ; 5b
        dg ---X-X-X
        dg ---XXXXX
        dg -----X-X
        dg ----XXXX
        dg -----X-X
        dg --X---X-
        dg ---X---X
        dg ----X-X-

        ; 5c
        dg -X-X-X-X
        dg XXXXXXXX
        dg -X-X-X-X
        dg X-X-X-X-
        dg -X-X-X-X
        dg X-X-X-X-
        dg -X-X-X-X
        dg X-X-XXXX

        ; 5d
        dg -X-X-X-X
        dg XXXXXXXX
        dg -X-X-X-X
        dg X-X-X-XX
        dg -X-X-X-X
        dg XXX-XXXX
        dg -X-X-X-X
        dg XXXXXXXX

        ; 5e
        dg -X-X-X-X
        dg XXXXXXXX
        dg -X-X-X-X
        dg X-XXX-XX
        dg -X-X-X-X
        dg XXXXXXXX
        dg -X-X-X-X
        dg XXXXXXXX

        ; 5f
        dg -X-X-X-X
        dg XXXXXXXX
        dg -X-X-X-X
        dg XXXXXXXX
        dg -X-X-X-X
        dg XXXXXXXX
        dg -X-X-X-X
        dg XXXXXXXX

        ; 60
        dg -X-X-X-X
        dg XXXXXXXX
        dg -X-X-X-X
        dg XXXXXXXX
        dg -X-X-XXX
        dg XXXXXXXX
        dg -XXXXXXX
        dg XXXXXXXX

        ; 61
        dg --------
        dg ----XX--
        dg -X-X---X
        dg X-XX--X-
        dg -X---X-X
        dg X-X-X-X-
        dg -X-X-X--
        dg X-X-XX--

        ; 62
        dg ---X----
        dg X-XX----
        dg -X------
        dg X-------
        dg --------
        dg --------
        dg --------
        dg --------

        ; 63
        dg --------
        dg --------
        dg -------X
        dg ----X--X
        dg ---X-X-X
        dg --X--X-X
        dg -X----X-
        dg X------X

        ; 64
        dg ----X---
        dg ----X---
        dg ----X---
        dg ----X---
        dg ----X--X
        dg X---XX--
        dg X---X---
        dg X----X--

        ; 65
        dg --X----X
        dg --X---X-
        dg ---X--X-
        dg -X-X--X-
        dg ---X---X
        dg ----X--X
        dg -----X--
        dg X-X---XX

        ; 66
        dg ----X---
        dg ----X--X
        dg ----X--X
        dg ----X--X
        dg -----X--
        dg ------X-
        dg X------X
        dg -X------

        ; 67
        dg XX--X---
        dg -X--XXX-
        dg -X---XX-
        dg --X--X-X
        dg X--X-X--
        dg -X-X--X-
        dg -X--X-X-
        dg X-X--X--

        ; 68
        dg X-------
        dg XX-----X
        dg X-X----X
        dg -X-X----
        dg X---XX--
        dg ------XX
        dg --------
        dg --------

        ; 69
        dg --------
        dg --------
        dg --------
        dg X-------
        dg -X----X-
        dg XXX---X-
        dg ---XX--X
        dg -----X-X

        ; 6a
        dg -----X-X
        dg ----X-X-
        dg -----X-X
        dg -----XX-
        dg -------X
        dg -------X
        dg --------
        dg XXXX----

        ; 6b
        dg -X-X-X-X
        dg X-XXXXXX
        dg -X-X-X-X
        dg XXXXXXXX
        dg -X-XXX-X
        dg XXXXXXXX
        dg -X-XXXXX
        dg --XXXXXX

        ; 6c
        dg -X-XXX-X
        dg XXXXXXXX
        dg -XXX-XXX
        dg XXXXXXXX
        dg XXXXXXXX
        dg XXXXXXXX
        dg XXXXXXXX
        dg XXXXXXXX

        ; 6d
        dg -X-X----
        dg XXXXX---
        dg -X-X---X
        dg XXXX---X
        dg -X-X---X
        dg XXX--XXX
        dg XXX--X-X
        dg XXX-XXXX

        ; 6e
        dg -X-----X
        dg XX-----X
        dg -X------
        dg XX----X-
        dg -----X-X
        dg X----XXX
        dg -----X-X
        dg X---XXXX

        ; 6f
        dg ------XX
        dg ----XXX-
        dg ---XX---
        dg --XX----
        dg ------XX
        dg -----XXX
        dg ----XXX-
        dg ---XX--X

        ; 70
        dg X----XXX
        dg X----XX-
        dg -X----X-
        dg XXX---X-
        dg XX-X---X
        dg ---X---X
        dg -XXXX--X
        dg XXX--X--

        ; 71
        dg X-------
        dg -------X
        dg ----X---
        dg -XX-----
        dg XX------
        dg -------X
        dg ----X-X-
        dg X--X-X-X

        ; 72
        dg X-------
        dg --------
        dg --------
        dg -----X-X
        dg --X-X-X-
        dg -X-X-X--
        dg X-X-X---
        dg -X------

        ; 73
        dg -X------
        dg ---X-X-X
        dg X-X-----
        dg -X-----X
        dg --------
        dg --------
        dg ------X-
        dg ------XX

        ; 74
        dg X-X-X-X-
        dg -X-X----
        dg ------X-
        dg -X-X-X-X
        dg --X-X-X-
        dg -X-X-X-X
        dg --X-X-X-
        dg -X-X-X-X

        ; 75
        dg X-X-X-X-
        dg ---X-X-X
        dg X-X-X-X-
        dg -X-X-X-X
        dg X-X-X-X-
        dg -X-X-X-X
        dg X-X-X-X-
        dg -X-X-X-X

        ; 76
        dg -------X
        dg --------
        dg X-------
        dg -X------
        dg X-----X-
        dg -X-----X
        dg X-X---X-
        dg -X-X---X

        ; 77
        dg XXXXX---
        dg X----X--
        dg --X---X-
        dg -X-X----
        dg --X-X-X-
        dg -----X-X
        dg ------X-
        dg -X-----X

        ; 78
        dg -X-XXXXX
        dg -XXXXXXX
        dg ---XXXXX
        dg ---XXXXX
        dg -----XXX
        dg --X--XXX
        dg ---X---X
        dg ---XXXXX

        ; 79
        dg XXXXXXXX
        dg XXXXXXXX
        dg XXXXXX-X
        dg XXXXXXXX
        dg X-XX-X-X
        dg XXXXXXXX
        dg -X-X-X-X
        dg XXXXXXXX

        ; 7a
        dg XXXXXXXX
        dg XXXXXXXX
        dg -X-X-X-X
        dg XXXXXXXX
        dg -X-X-X-X
        dg XXXXXXXX
        dg -X-X-X-X
        dg XXX-X-X-

        ; 7b
        dg XXXXXXX-
        dg XXXXXXXX
        dg -X-X-X-X
        dg XXXXXXXX
        dg -X-X-X-X
        dg XXXXXXXX
        dg -X------
        dg X--X-X-X

        ; 7c
        dg XXXX-X-X
        dg XXXXXXXX
        dg -X-X-X-X
        dg XXXXXXXX
        dg -X-X-X-X
        dg -----XXX
        dg X-X----X
        dg -XX--X--

        ; 7d
        dg -X--XXXX
        dg XXX-XXXX
        dg -X-X-X-X
        dg XXXXXXXX
        dg -X-X-X-X
        dg X-X-XXXX
        dg -X-X-X-X
        dg XXX-X-X-

        ; 7e
        dg X---XXXX
        dg X---XXXX
        dg ---XXXXX
        dg X--XXXXX
        dg ---X-X-X
        dg X--XXXXX
        dg -X-X-X-X
        dg X---XXX-

        ; 7f
        dg ------XX
        dg X----XXX
        dg X---XX--
        dg X-------
        dg -X-----X
        dg XX----XX
        dg -X---XXX
        dg X-X-X-X-

        ; 80
        dg X-----XX
        dg -----X--
        dg ---XXXXX
        dg -XXXXXXX
        dg XXXXXXXX
        dg XXXX---X
        dg X-------
        dg --------

        ; 81
        dg --X-X-X-
        dg X--X-X-X
        dg X-X-----
        dg -X------
        dg X-X-----
        dg XX-X----
        dg X-X-X-X-
        dg XX-X-X-X

        ; 82
        dg X-------
        dg -------X
        dg --------
        dg ----X---
        dg -----X--
        dg --X-----
        dg -XXXXXXX
        dg -X---X-X

        ; 83
        dg -XX---XX
        dg XX----X-
        dg -----XXX
        dg -----XX-
        dg ----XXX-
        dg --XXXX-X
        dg XX-X--X-
        dg -----X-X

        ; 84
        dg --X-X-X-
        dg -X-X-X--
        dg --X-----
        dg -X---X-X
        dg X---X-X-
        dg -X-X-X-X
        dg X-X-X-X-
        dg -X-X-X-X

        ; 85
        dg X-X-X-X-
        dg -X-X-X-X
        dg X-X-X-X-
        dg -X-X-X-X
        dg X-X-X-X-
        dg -X-X-X-X
        dg X-X-X-X-
        dg -X-X-X-X

        ; 86
        dg X-X-X---
        dg -X-X----
        dg X-X-X---
        dg -X-X-X--
        dg X-X-X-X-
        dg -X-X-X-X
        dg X-X-X-X-
        dg -X-X-X-X

        ; 87
        dg X-X-X---
        dg ---X-X--
        dg --X-X-X-
        dg ---X-X--
        dg ----X---
        dg --------
        dg X-------
        dg --------

        ; 88
        dg -----X-X
        dg -----XXX
        dg -------X
        dg ----X---
        dg -----X--
        dg ----XXX-
        dg -----X-X
        dg -----XXX

        ; 89
        dg -X-X-X-X
        dg XXXXXXX-
        dg -X-X-X-X
        dg XXXXXXXX
        dg -X-X-X-X
        dg -XXXXXX-
        dg -X-XXX-X
        dg -XXXX-XX

        ; 8a
        dg -X-X-X--
        dg X-X-X--X
        dg -X----XX
        dg X--X-XXX
        dg -XXXXXXX
        dg XXXXXXXX
        dg XXXXXXXX
        dg XXXXXXX-

        ; 8b
        dg -X-XXXXX
        dg -XXXXXXX
        dg XXXXXXX-
        dg XXXXXX--
        dg XXXXX---
        dg X-XX---X
        dg -XX---X-
        dg X-X----X

        ; 8c
        dg XX--X--X
        dg X--X-X--
        dg --X-X--X
        dg -X-X-X--
        dg X-X-X--X
        dg -X-X--XX
        dg X-X-X---
        dg -X-X---X

        ; 8d
        dg -X-X-X-X
        dg XXXXXXXX
        dg -X-X-X-X
        dg XXXXXXXX
        dg XX-X-X-X
        dg XXXXXXXX
        dg XXX-XXXX
        dg XXXXXXXX

        ; 8e
        dg -X-X-X-X
        dg XX--X-X-
        dg -X-X-X-X
        dg XXX-XXXX
        dg -X-X-X-X
        dg XXXXXXXX
        dg -X-X-X-X
        dg XXXXXXXX

        ; 8f
        dg -X------
        dg X-X-----
        dg -X------
        dg XXX-----
        dg -X-X----
        dg XXXXX---
        dg XXX-XX--
        dg XXXXXXX-

        ; 90
        dg --------
        dg -------X
        dg -XX----X
        dg -X-----X
        dg -----X-X
        dg X---X-X-
        dg -X---X-X
        dg --XXX-X-

        ; 91
        dg -XX-X-X-
        dg -X-X-X-X
        dg -XX-X-X-
        dg -X-X-X-X
        dg -XX-X-X-
        dg -X-X-X-X
        dg -XX-X-X-
        dg -X-X-X-X

        ; 92
        dg X-X-X-X-
        dg -X-X-X-X
        dg X-X-X-X-
        dg -X-X-X-X
        dg X-X-X-X-
        dg -X-X-X-X
        dg X-X-X-X-
        dg -X-X-X-X

        ; 93
        dg X-X-X-X-
        dg -X-X-X-X
        dg X-X-X-X-
        dg -X-X-X-X
        dg X-X-X-X-
        dg -X-X-X--
        dg X-X-X--X
        dg -X-X--X-

        ; 94
        dg X-------
        dg --------
        dg X-------
        dg --------
        dg --------
        dg --------
        dg --------
        dg --------

        ; 95
        dg -------X
        dg --X---XX
        dg -------X
        dg ----X--X
        dg --------
        dg -----X--
        dg ------XX
        dg --------

        ; 96
        dg -XXX-XXX
        dg XXX-XXXX
        dg -X-XXX-X
        dg --XXX-XX
        dg ---X-X-X
        dg X-X-X-X-
        dg ---X-X-X
        dg --X-X-X-

        ; 97
        dg XXXX-X-X
        dg XXX-X-X-
        dg XX-X----
        dg X-X---XX
        dg -X---XXX
        dg X--XXXXX
        dg ---X-X-X
        dg -XXXXXXX

        ; 98
        dg -X------
        dg -----X--
        dg -X----XX
        dg XXX--X-X
        dg XXX---X-
        dg XXX--X-X
        dg XXXX----
        dg XXXX---X

        ; 99
        dg X-X---XX
        dg ---XXXXX
        dg XXXXXXXX
        dg XXXXXXXX
        dg XXXXXXXX
        dg -XXXXXXX
        dg X-X-XXXX
        dg -X-X-X-X

        ; 9a
        dg -----X-X
        dg X---X-XX
        dg XX---XXX
        dg XXX-XXXX
        dg XXX--XXX
        dg XXX--XXX
        dg XXX--XXX
        dg XXXX--XX

        ; 9b
        dg -XX-X-X-
        dg -X-X-X-X
        dg -X--X-X-
        dg ---X-X-X
        dg -XX-X-X-
        dg -XXX-X--
        dg X-XXX---
        dg XX---X-X

        ; 9c
        dg X-X-X-X-
        dg -X-X-X-X
        dg X-X-X-X-
        dg -X-X-X-X
        dg ----X-X-
        dg -X-X-X-X
        dg X---X-X-
        dg ---X-X-X

        ; 9d
        dg X-X-----
        dg -X-X-X--
        dg X-X-X---
        dg -X-X----
        dg X-X---X-
        dg -X---X--
        dg X-X-X-X-
        dg -X---X--

        ; 9e
        dg --------
        dg --------
        dg -----X--
        dg ------X-
        dg --X-----
        dg --------
        dg ---X---X
        dg ----X--X

        ; 9f
        dg -X---X--
        dg ----X---
        dg -------X
        dg -----XXX
        dg ---X-X-X
        dg --XXXXX-
        dg ---X-X-X
        dg X--XX-X-

        ; a0
        dg -X-XXXXX
        dg XXXX----
        dg -X-X----
        dg XXXX----
        dg -X-X----
        dg X-XX----
        dg -X-X----
        dg X-XX----

        ; a1
        dg XXXX----
        dg ---XXXX-
        dg -----X-X
        dg -----XXX
        dg -----XXX
        dg -----XXX
        dg -----XXX
        dg -----XXX

        ; a2
        dg --X---X-
        dg --------
        dg -X-X-XXX
        dg XXXXXXXX
        dg XXXXXXXX
        dg XXXXXXXX
        dg XXXXXXXX
        dg XXXXXXXX

        ; a3
        dg XXX-XXXX
        dg XXXXXXXX
        dg -X-X-X-X
        dg XXXXXXXX
        dg -XXXXX-X
        dg XX---XXX
        dg XX---XXX
        dg XX---XXX

        ; a4
        dg -X-X-X-X
        dg XXXXXXXX
        dg -X-X-X-X
        dg XXXXXXXX
        dg -XXXXXXX
        dg XXXXXXXX
        dg XXXXXXXX
        dg XXX-X-X-

        ; a5
        dg -X-X-XXX
        dg XXXXXXXX
        dg -X-X-X-X
        dg XXXXXXXX
        dg XX-X-X-X
        dg XXXXXXXX
        dg XXXXXXXX
        dg XXXXXXXX

        ; a6
        dg -XXX--XX
        dg XXXXX--X
        dg -X-X---X
        dg XXXXXX--
        dg -X-X-X--
        dg XXXXXXX-
        dg XXXXXXXX
        dg XXXXXXXX

        ; a7
        dg XXXXX---
        dg XXXXXX-X
        dg XXXXXXXX
        dg XXXXXXXX
        dg XXXXXXXX
        dg -XXXXXXX
        dg --XXXXXX
        dg X--XXXXX

        ; a8
        dg X-X-X-X-
        dg -X-X-X-X
        dg XXX-X-X-
        dg XXXXX---
        dg XXX---X-
        dg XX-XXX-X
        dg XXXXXXX-
        dg XXXXXXXX

        ; a9
        dg X-X-X-X-
        dg -X-X-X-X
        dg ----X-X-
        dg -X-X-X-X
        dg X-X-X-X-
        dg -X-X-X-X
        dg X-X-X-X-
        dg -X-X-X-X

        ; aa
        dg X-X-X---
        dg -X-X-X--
        dg X-X-X---
        dg -X-X----
        dg X-X-----
        dg -X------
        dg X---X-X-
        dg -------X

        ; ab
        dg --------
        dg -X------
        dg --------
        dg --------
        dg X-X----X
        dg -X-X----
        dg X-X-X-X-
        dg -X-X-X-X

        ; ac
        dg -----X--
        dg X-----X-
        dg -X-----X
        dg -----X--
        dg -----X--
        dg XX------
        dg -X------
        dg --------

        ; ad
        dg X--XXX-X
        dg -----XXX
        dg ------XX
        dg ----X-XX
        dg -----X-X
        dg -----X-X
        dg ----XX-X
        dg --XXX-XX

        ; ae
        dg -X-X----
        dg XXXX----
        dg -XX-----
        dg XX------
        dg X-------
        dg X-------
        dg X-------
        dg X-------

        ; af
        dg XX-X-XX-
        dg -XXXXXXX
        dg -X-X-X-X
        dg -XX-----
        dg --------
        dg --------
        dg --------
        dg --------

        ; b0
        dg XX---XXX
        dg XX---XXX
        dg -----X-X
        dg ------XX
        dg --------
        dg --------
        dg --------
        dg --------

        ; b1
        dg -X-X-X-X
        dg XXXXXXXX
        dg -XXXXX--
        dg XX------
        dg --------
        dg --------
        dg --------
        dg --------

        ; b2
        dg -X-X-X-X
        dg XXXXXXXX
        dg -X-X-X-X
        dg --XXXXXX
        dg --------
        dg --------
        dg --------
        dg --------

        ; b3
        dg -X-X-X-X
        dg XXXXX-X-
        dg XX-X-X-X
        dg --X-XXXX
        dg --------
        dg --------
        dg --------
        dg --------

        ; b4
        dg -X--XXXX
        dg X-X--XXX
        dg -X-X--XX
        dg XXXXX--X
        dg -----X--
        dg ------X-
        dg -------X
        dg --------

        ; b5
        dg XXXXXXXX
        dg XXXXXXXX
        dg XXXXXXXX
        dg XXXXXXX-
        dg XXXXXXXX
        dg -XXXXXXX
        dg --XXXXXX
        dg X--XXXXX

        ; b6
        dg X-X-X-X-
        dg -X---X-X
        dg X---X-X-
        dg ---X-X-X
        dg --X-X-X-
        dg XX-X-X-X
        dg X-X-X-X-
        dg XX-X-X-X

        ; b7
        dg X-X-X-X-
        dg -X-X-X--
        dg X-X-X---
        dg -X-X----
        dg X-X---X-
        dg -X------
        dg X-----X-
        dg -X------

        ; b8
        dg --X-X-X-
        dg -----X-X
        dg --X-X-X-
        dg ---X-X-X
        dg X-X-X-X-
        dg -X-X-X-X
        dg X-X-X-X-
        dg -X-X-X-X

        ; b9
        dg X-X-X-X-
        dg -X-X-X-X
        dg X-X-X-X-
        dg -X-X-X--
        dg X-X-----
        dg -X------
        dg X------X
        dg ------XX

        ; ba
        dg --------
        dg -------X
        dg ------X-
        dg ----XX--
        dg --XX---X
        dg -X----X-
        dg X----X--
        dg ----X---

        ; bb
        dg -XXX---X
        dg XXX---X-
        dg -X-----X
        dg X---X-X-
        dg ---X-XXX
        dg --X-XXXX
        dg -XXXXXXX
        dg XXXXXXXX

        ; bc
        dg --------
        dg --------
        dg -XXX-X-X
        dg XXXXXXX-
        dg XXXXXX-X
        dg XXXXXXX-
        dg XXXXXXX-
        dg XXXXXX--

        ; bd
        dg -X--XXXX
        dg --X-XXXX
        dg --X--XXX
        dg ---X--XX
        dg ----X--X
        dg -----X--
        dg ------X-
        dg -------X

        ; be
        dg XXX-X-X-
        dg XXXX-X-X
        dg XXXXX-X-
        dg XXXXXX-X
        dg XXXXXXXX
        dg XXXXXXXX
        dg -XXXXXXX
        dg ---XXXXX

        ; bf
        dg X-X-X-X-
        dg -X-X-X-X
        dg X-X-X-X-
        dg -X-X-X--
        dg X-X-X---
        dg XXXX----
        dg XX------
        dg --------

        ; c0
        dg X---X-X-
        dg -------X
        dg ----X-X-
        dg -------X
        dg X-X-X-X-
        dg -----X--
        dg X-X-X---
        dg ---X----

        ; c1
        dg X-X-X---
        dg -X-X----
        dg X-X-----
        dg -X------
        dg X-------
        dg -------X
        dg -----XXX
        dg ----XX--

        ; c2
        dg -----XX-
        dg ---XXX--
        dg --XX----
        dg -XX-----
        dg XX----XX
        dg X----XX-
        dg ----XX--
        dg ---XX---

        ; c3
        dg ---X---X
        dg --X---XX
        dg -X---XXX
        dg X---XXXX
        dg ---XXXXX
        dg --XXXXXX
        dg -XXXXXXX
        dg X-XXXXXX

        ; c4
        dg XXXXXX--
        dg XXXXX---
        dg XXXX----
        dg XXXX----
        dg XXX-----
        dg XX------
        dg X-------
        dg X-------

        ; c5
        dg -------X
        dg -------X
        dg ------XX
        dg ------XX
        dg -----XXX
        dg ------XX
        dg -----XXX
        dg ----XXXX

        ; c6
        dg XX------
        dg --XXXXXX
        dg -------X
        dg -------X
        dg ------X-
        dg ----XX-X
        dg ---X--XX
        dg --X-XXX-

        ; c7
        dg ------X-
        dg --------
        dg X-------
        dg XX------
        dg XX------
        dg X----X--
        dg --------
        dg ---X----

        ; c8
        dg X-X-----
        dg --------
        dg X-------
        dg -------X
        dg ------XX
        dg -----XX-
        dg ----XX--
        dg --XXX---

        ; c9
        dg ---XX---
        dg -XXX----
        dg XX-----X
        dg X-----X-
        dg -----X-X
        dg ----X-X-
        dg -X-X-X-X
        dg X-X-X-X-

        ; ca
        dg -XXX---X
        dg XXX---X-
        dg -X---X-X
        dg X-X---XX
        dg -X---X-X
        dg X---X-XX
        dg ---X-X-X
        dg ----X-X-

        ; cb
        dg -XXXXXXX
        dg XXXXXXXX
        dg XXXXXXXX
        dg XXXXXXXX
        dg XXXXXXXX
        dg XXXXXXXX
        dg XXXXXXXX
        dg X-XXXXX-

        ; cc
        dg XXXXXXXX
        dg XXXXXXXX
        dg XXXXXXX-
        dg XXXXX-X-
        dg XXXX-X--
        dg XXX-X---
        dg XX-X-X--
        dg X-X-X---

        ; cd
        dg -----XXX
        dg ----XXXX
        dg ---X-XXX
        dg ----XXXX
        dg ---XXXXX
        dg --X-XXXX
        dg ---XXXXX
        dg --X-XXXX

        ; ce
        dg -X-X-X--
        dg X-XXXXX-
        dg --X-XX-X
        dg ------XX
        dg --X-----
        dg -XXX----
        dg -XXXX---
        dg --XXXX--

        ; cf
        dg -XXXXXXX
        dg XXX-X-X-
        dg -X------
        dg -----X-X
        dg --X-X-X-
        dg -X-XXXXX
        dg --XXXXXX
        dg -XXXXXXX

        ; d0
        dg XXXXXXXX
        dg X-X-XXXX
        dg -----X-X
        dg -X-X----
        dg X-X-X-X-
        dg XXXXXX-X
        dg XXXXXXXX
        dg XXXXXXXX

        ; d1
        dg X-X-X-X-
        dg XXXXXXX-
        dg XXXXXXXX
        dg X-XXXXXX
        dg --X-XXXX
        dg -X--X-XX
        dg X-X---X-
        dg XXXX-X--

        ; d2
        dg --X-X-X-
        dg X----X--
        dg X-X-----
        dg XX-X----
        dg XXX-X---
        dg XXXX-X--
        dg XXXXX---
        dg X-XXXX--

        ; d3
        dg X-XXX---
        dg XX-X-XX-
        dg XX--XX-X
        dg -X---XX-
        dg XX--XXXX
        dg -XX--XXX
        dg XXX-X-XX
        dg -XXX-X-X

        ; d4
        dg --XXXXXX
        dg -X--XXXX
        dg --XX--XX
        dg X--XXX--
        dg -X--XXXX
        dg X-X--X-X
        dg XX-XX---
        dg XXXX-X-X

        ; d5
        dg XXXXXXXX
        dg XXXXXXXX
        dg XXXXXXXX
        dg -XXXXXXX
        dg X-------
        dg XXXXXXXX
        dg X-X-X-X-
        dg --------

        ; d6
        dg XXXXX-X-
        dg XXXXXX-X
        dg XXXXXX--
        dg XXX---X-
        dg ---XXX--
        dg XXXXX---
        dg X-X---X-
        dg ---X-X-X

        ; d7
        dg -X-XX---
        dg --XX----
        dg ----X---
        dg --XXX-X-
        dg -XXX---X
        dg XXXX--X-
        dg XXX--X-X
        dg XX--X-X-

        ; d8
        dg --------
        dg --------
        dg --------
        dg --------
        dg --------
        dg X-------
        dg -X------
        dg X-X-----

        ; d9
        dg X-XXX-X-
        dg -XXXXX-X
        dg --XXXXX-
        dg -X-XXXXX
        dg --X-XXXX
        dg X--X-XXX
        dg -X--X-X-
        dg X-X--X-X

        ; da
        dg XXXXXXX-
        dg -X-XXXXX
        dg --X-X-XX
        dg X----X-X
        dg XXXX----
        dg XXXXXXX-
        dg XXXXXXXX
        dg -X-XX-XX

        ; db
        dg X-X-X-X-
        dg XXXXXXXX
        dg XXXXXXXX
        dg -XXXXXXX
        dg X-X-X-X-
        dg --------
        dg XXXXXXXX
        dg -X-X-X-X

        ; dc
        dg X-X-XXXX
        dg XXXXXX-X
        dg XXXXX-X-
        dg XX-X----
        dg X-X---XX
        dg ----XX-X
        dg XXXXX-X-
        dg -X-X-X--

        ; dd
        dg X--XXXXX
        dg --XXXXXX
        dg -XXXXXXX
        dg XXXX-XXX
        dg X-X---XX
        dg ---XXX-X
        dg -XXXXXXX
        dg XXXXXXXX

        ; de
        dg -X-X----
        dg XXX-X---
        dg XXXX-X--
        dg XXXXX-X-
        dg XXXXXX-X
        dg XXXXX-X-
        dg XXXXXX-X
        dg XXXXX-X-

        ; df
        dg ----XXXX
        dg -X-----X
        dg --XX----
        dg X--XXX--
        dg -X--XXXX
        dg X-X--X-X
        dg XX-XX---
        dg XXXX-X-X

        ; e0
        dg XXXXXXXX
        dg XXXXXXXX
        dg ---XXXXX
        dg --------
        dg X-------
        dg XXXXXXXX
        dg X-X-X-X-
        dg --------

        ; e1
        dg XXXXX-X-
        dg XXXXXX-X
        dg XXXX----
        dg ------X-
        dg ---XXX--
        dg XXXXX---
        dg X-X---X-
        dg ---X-X-X

        ; e2
        dg -XXXXXXX
        dg XXX-X-X-
        dg -X------
        dg -----X-X
        dg --X-X-X-
        dg -X-XXXXX
        dg --XX----
        dg --------

        ; e3
        dg XXXXXXXX
        dg X-X-XXXX
        dg -----X-X
        dg -X-X----
        dg X-X-X-X-
        dg XXXXXX-X
        dg -------X
        dg --------

        ; e4
        dg X-X-X-X-
        dg XXXXXXX-
        dg XXXXXXXX
        dg X-XXXXXX
        dg --X-XXXX
        dg -X--X-XX
        dg X-X---X-
        dg --XX-X--

        ; e5
        dg --------
        dg -X------
        dg --X-----
        dg X--X----
        dg -X--XXX-
        dg X-X--X-X
        dg XX-XX---
        dg XXXX-X-X

        ; e6
        dg -------X
        dg ------XX
        dg ------XX
        dg -------X
        dg --------
        dg XXXXXXXX
        dg X-X-X-X-
        dg --------

        ; e7
        dg X---X-X-
        dg XXX--X-X
        dg XXXX----
        dg XXX---X-
        dg ----XX--
        dg XXXXX---
        dg X-X---X-
        dg ---X-X-X

        ; e8
        dg -XXXXXXX
        dg XXX-X-X-
        dg -X------
        dg ----XXXX
        dg --XX----
        dg -X------
        dg --------
        dg --------

        ; e9
        dg XXXXXXXX
        dg X-X-XXXX
        dg -----X-X
        dg XXXX----
        dg ----XXX-
        dg -------X
        dg --XXXX--
        dg --XXXXXX

        ; ea
        dg X-X-X-X-
        dg XXXXXXX-
        dg XXXXXXXX
        dg X-XXXXXX
        dg --X-XXXX
        dg XX--X-XX
        dg --XX--X-
        dg X---XX--

        ; eb
        dg --------
        dg --------
        dg --------
        dg X-------
        dg -X------
        dg X-X-----
        dg XX-XX---
        dg XXXX-X-X

        ; ec
        dg --XXXXXX
        dg ---XXXXX
        dg ---XXXXX
        dg ----XXXX
        dg -----XXX
        dg --------
        dg --------
        dg --------

        ; ed
        dg XXX---X-
        dg XXXXX--X
        dg XXXX----
        dg XXX-----
        dg XX------
        dg --------
        dg ------X-
        dg ---X-X-X

