; unprocessed labels
X6a7b equ 0x6a7b
Ljoy_flag_002 equ 0x5c06 ; sic

L6667 equ 0x6667

X831f equ Wait_fire_some_time
X8321 equ Wait_fire_custom
X61e5 equ Print_something_custom

X8330 equ Delay
X8333 equ Delay_custom

; im2
X853f equ 0x853f

X8e77 equ 0x8e77


;smc_L865b equ beep_dur0
;smc_L865d equ beep_dur1

; magic_vars im2_always
L8557 equ mv1
L8558 equ mv2
L8559 equ mv3
L855a equ mv4

L8683 equ 0x8683 ; some 12-byte table?

L8454 equ maybe_sound_to_play

;L8454_is_ff equ 0x8634

L6602 equ 0x6602

L69e3 equ 0x69e3

smc_L9ba3 equ 0x9ba3

L6b5c equ 0x6b5c
X70ef equ 0x70ef

Pre_game_animations equ 0xa73e
Xa73e equ Pre_game_animations


; variables from after-table initializer:
L69df equ 0x69df
L5d02 equ 0x5d02
L8452 equ 0x8452
L8dfe equ 0x8dfe

X5fc0 equ 0x5fc0
Xa65d equ 0xa65d
X95c3 equ 0x95c3
Xffeb equ 0xffeb

smc_L88ae equ 0x88ae
smc_L845f equ 0x845f
smc_L878f equ 0x878f

; abstract addresses, not matching actual source
L5fee equ 0x5fee ; V
L5ff7 equ 0x5ff7 ; V

L7f1d equ 0x7f1d
L80eb equ 0x80eb

L6bdd equ 0x6bdd ; V
