        ; 20 = " "
        dg --------
        dg --------
        dg --------
        dg --------
        dg --------
        dg --------
        dg --------
        dg --------

        ; 21 = "!"
        dg ---XX---
        dg --XXXX--
        dg --XXXX--
        dg ---XX---
        dg ---XX---
        dg --------
        dg ---XX---
        dg --------
        ; 22 = """ ╔
        dg --------
        dg --------
        dg --------
        dg --XXXXXX
        dg --X-----
        dg --X-XXXX
        dg --X-X---
        dg --X-X---

        ; 23 = "#" ═
        dg --------
        dg --------
        dg --------
        dg XXXXXXXX
        dg --------
        dg XXXXXXXX
        dg --------
        dg --------

        ; 24 = "$" ╗
        dg --------
        dg --------
        dg --------
        dg XXXXX---
        dg ----X---
        dg XXX-X---
        dg --X-X---
        dg --X-X---

        ; 25 = "%" ║
        dg --X-X---
        dg --X-X---
        dg --X-X---
        dg --X-X---
        dg --X-X---
        dg --X-X---
        dg --X-X---
        dg --X-X---

        ; 26 = "&"
        dg --------
        dg -XX-XX--
        dg -XX-XX--
        dg --XXX---
        dg --XXX---
        dg -XX-XX--
        dg -XX-XX--
        dg --------


        ; 27 = "'" ╚
        dg --X-X---
        dg --X-XXXX
        dg --X-----
        dg --XXXXXX
        dg --------
        dg --------
        dg --------
        dg --------

        ; 28 = "(" ═
        dg --------
        dg XXXXXXXX
        dg --------
        dg XXXXXXXX
        dg --------
        dg --------
        dg --------
        dg --------

        ; 29 = ")" ╝
        dg --X-X---
        dg XXX-X---
        dg ----X---
        dg XXXXX---
        dg --------
        dg --------
        dg --------
        dg --------

        ; 2a = "*"
        dg --------
        dg --XXXXX-
        dg --XX----
        dg --XXXX--
        dg --XX----
        dg --XX----
        dg --XX----
        dg --------

        ; 2b = "+"
        dg XXX-----
        dg X-------
        dg XX---XX-
        dg X----X-X
        dg XXX--X-X
        dg -----X-X
        dg -----XX-
        dg --------

        ; 2c = ","
        dg --------
        dg --------
        dg --------
        dg --------
        dg --------
        dg ---XX---
        dg ---XX---
        dg --XX----

        ; 2d = "-"
        dg --------
        dg --------
        dg --------
        dg --------
        dg --------
        dg --------
        dg XXXXXXX-
        dg --------

        ; 2e = "."
        dg --------
        dg --------
        dg --------
        dg --------
        dg --------
        dg ---XX---
        dg ---XX---
        dg --------

        ; 2f = "/"
        dg XXXXXXXX
        dg --------
        dg --------
        dg --------
        dg --------
        dg --------
        dg --------
        dg --------

        ; 30 = "0"
        dg --XXX---
        dg -XX-XX--
        dg XX---XX-
        dg XX---XX-
        dg XX---XX-
        dg -XX-XX--
        dg --XXX---
        dg --------

        ; 31 = "1"
        dg ---XX---
        dg --XXX---
        dg ---XX---
        dg ---XX---
        dg ---XX---
        dg ---XX---
        dg -XXXXXX-
        dg --------

        ; 32 = "2"
        dg -XXXXX--
        dg XX---XX-
        dg -----XX-
        dg --XXXX--
        dg -XX-----
        dg XX------
        dg XXXXXXX-
        dg --------

        ; 33 = "3"
        dg XXXXXXX-
        dg ----XX--
        dg ---XX---
        dg --XXXX--
        dg -----XX-
        dg XX---XX-
        dg -XXXXX--
        dg --------

        ; 34 = "4"
        dg ---XXX--
        dg --XXXX--
        dg -XX-XX--
        dg XX--XX--
        dg XXXXXXX-
        dg ----XX--
        dg ----XX--
        dg --------

        ; 35 = "5"
        dg XXXXXXX-
        dg XX------
        dg XX------
        dg XXXXXX--
        dg -----XX-
        dg XX---XX-
        dg -XXXXX--
        dg --------

        ; 36 = "6"
        dg --XXXX--
        dg -XX-----
        dg XX------
        dg XXXXXX--
        dg XX---XX-
        dg XX---XX-
        dg -XXXXX--
        dg --------

        ; 37 = "7"
        dg XXXXXXX-
        dg XX---XX-
        dg ----XX--
        dg ---XX---
        dg --XX----
        dg --XX----
        dg --XX----
        dg --------

        ; 38 = "8"
        dg -XXXX---
        dg XX---X--
        dg XXX--X--
        dg -XXXX---
        dg X-XXXXX-
        dg X----XX-
        dg -XXXXX--
        dg --------

        ; 39 = "9"
        dg -XXXXX--
        dg XX---XX-
        dg XX---XX-
        dg -XXXXXX-
        dg -----XX-
        dg ----XX--
        dg -XXXX---
        dg --------

        ; 3a = ":"
        dg --------
        dg ---X-XX-
        dg --------
        dg ----X-XX
        dg --------
        dg ---X-XX-
        dg --------
        dg --------

        ; 3b = ";"
        dg --------
        dg XXXX----
        dg --------
        dg -XXXX---
        dg --------
        dg XXXX----
        dg --------
        dg --------

        ; 3c = "<"
        dg ---X----
        dg --XX----
        dg -XXXXXX-
        dg XXXXXXX-
        dg -XXXXXX-
        dg --XX----
        dg ---X----
        dg --------

        ; 3d = "="
        dg --------
        dg -------X
        dg -----XXX
        dg ----XX-X
        dg -----XXX
        dg -------X
        dg --------
        dg --------

        ; 3e = ">"
        dg --------
        dg XXXX----
        dg --------
        dg XXXX----
        dg --------
        dg XXXX----
        dg --------
        dg --------

        ; 3f = "?"
        dg ---X-XXX
        dg X---XXX-
        dg XXX-XX-X
        dg XXXXXXXX
        dg XXX-XX-X
        dg X---XXX-
        dg ---X-XXX
        dg --------

        ; 40 = "@"
        dg --------
        dg --XX----
        dg XXXXXX--
        dg XXXXXXXX
        dg XXXXXX--
        dg --XX----
        dg --------
        dg --------

        ; 41 = "A"
        dg --XXX---
        dg -XX-XX--
        dg XX---XX-
        dg XX---XX-
        dg XXXXXXX-
        dg XX---XX-
        dg XX---XX-
        dg --------

        ; 42 = "B"
        dg XXXXX---
        dg XX--XX--
        dg XX--XX--
        dg XXXXXX--
        dg XX---XX-
        dg XX---XX-
        dg XXXXXX--
        dg --------

        ; 43 = "C"
        dg --XXXX--
        dg -XX--XX-
        dg XX------
        dg XX------
        dg XX------
        dg -XX--XX-
        dg --XXXX--
        dg --------

        ; 44 = "D"
        dg XXXXX---
        dg XX--XX--
        dg XX---XX-
        dg XX---XX-
        dg XX---XX-
        dg XX--XX--
        dg XXXXX---
        dg --------

        ; 45 = "E"
        dg XXXXXXX-
        dg XX------
        dg XX------
        dg XXXXX---
        dg XX------
        dg XX------
        dg XXXXXXX-
        dg --------

        ; 46 = "F"
        dg XXXXXXX-
        dg XX------
        dg XX------
        dg XXXXX---
        dg XX------
        dg XX------
        dg XX------
        dg --------

        ; 47 = "G"
        dg --XXXX--
        dg -XX--XX-
        dg XX------
        dg XX--XXX-
        dg XX---XX-
        dg -XX--XX-
        dg --XXXXX-
        dg --------

        ; 48 = "H"
        dg XX---XX-
        dg XX---XX-
        dg XX---XX-
        dg XXXXXXX-
        dg XX---XX-
        dg XX---XX-
        dg XX---XX-
        dg --------

        ; 49 = "I"
        dg -XXXXXX-
        dg ---XX---
        dg ---XX---
        dg ---XX---
        dg ---XX---
        dg ---XX---
        dg -XXXXXX-
        dg --------

        ; 4a = "J"
        dg XXXXXXX-
        dg ----XX--
        dg ----XX--
        dg ----XX--
        dg ----XX--
        dg XX-XX---
        dg -XXX----
        dg --------

        ; 4b = "K"
        dg XX--XX--
        dg XX--XX--
        dg XX-XX---
        dg XXXX----
        dg XX-XX---
        dg XX--XX--
        dg XX---XX-
        dg --------

        ; 4c = "L"
        dg XX------
        dg XX------
        dg XX------
        dg XX------
        dg XX------
        dg XX------
        dg XXXXXXX-
        dg --------

        ; 4d = "M"
        dg XX---XX-
        dg XXX-XXX-
        dg XXXXXXX-
        dg XX-X-XX-
        dg XX---XX-
        dg XX---XX-
        dg XX---XX-
        dg --------

        ; 4e = "N"
        dg XX---XX-
        dg XXX--XX-
        dg XXXX-XX-
        dg XXXXXXX-
        dg XX-XXXX-
        dg XX--XXX-
        dg XX---XX-
        dg --------

        ; 4f = "O"
        dg -XXXXX--
        dg XX---XX-
        dg XX---XX-
        dg XX---XX-
        dg XX---XX-
        dg XX---XX-
        dg -XXXXX--
        dg --------

        ; 50 = "P"
        dg XXXXX---
        dg XX--XX--
        dg XX---XX-
        dg XX--XX--
        dg XXXXX---
        dg XX------
        dg XX------
        dg --------

        ; 51 = "Q"
        dg --XXX---
        dg -XX-XX--
        dg XX---XX-
        dg XX---XX-
        dg XX---XX-
        dg -XX-XX--
        dg --XXX-X-
        dg --------

        ; 52 = "R"
        dg XXXXX---
        dg XX--XX--
        dg XX---XX-
        dg XX--XX--
        dg XXXXX---
        dg XX--XX--
        dg XX---XX-
        dg --------

        ; 53 = "S"
        dg -XXXX---
        dg XX--XX--
        dg XX------
        dg -XXXXX--
        dg -----XX-
        dg XX---XX-
        dg -XXXXX--
        dg --------

        ; 54 = "T"
        dg -XXXXXX-
        dg ---XX---
        dg ---XX---
        dg ---XX---
        dg ---XX---
        dg ---XX---
        dg ---XX---
        dg --------

        ; 55 = "U"
        dg XX---XX-
        dg XX---XX-
        dg XX---XX-
        dg XX---XX-
        dg XX---XX-
        dg XX---XX-
        dg -XXXXX--
        dg --------

        ; 56 = "V"
        dg XX---XX-
        dg XX---XX-
        dg XX---XX-
        dg XX---XX-
        dg XX---XX-
        dg -XX-XX--
        dg --XXX---
        dg --------

        ; 57 = "W"
        dg XX---XX-
        dg XX---XX-
        dg XX---XX-
        dg XX-X-XX-
        dg XXXXXXX-
        dg XXX-XXX-
        dg XX---XX-
        dg --------

        ; 58 = "X"
        dg XX---XX-
        dg XXX-XXX-
        dg -XXXXX--
        dg --XXX---
        dg -XXXXX--
        dg XXX-XXX-
        dg XX---XX-
        dg --------

        ; 59 = "Y"
        dg XX---XX-
        dg XX---XX-
        dg XX---XX-
        dg -XXXXX--
        dg --XXX---
        dg --XXX---
        dg --XXX---
        dg --------

        ; 5a = "Z"
        dg XXXXXXX-
        dg ----XX--
        dg ---XX---
        dg --XX----
        dg -XX-----
        dg XX------
        dg XXXXXXX-
        dg --------

