        ; 20 = " "
        dg --------
        dg --------
        dg --------
        dg --------
        dg --------
        dg --------
        dg --------
        dg --------

        ; 21 = "!"
        dg ---XX---
        dg --XXXX--
        dg --XXXX--
        dg ---XX---
        dg ---XX---
        dg --------
        dg ---XX---
        dg --------
        ; 22 = """ ╔
        dg --------
        dg --------
        dg --------
        dg --XXXXXX
        dg --X-----
        dg --X-XXXX
        dg --X-X---
        dg --X-X---

        ; 23 = "#" ═
        dg --------
        dg --------
        dg --------
        dg XXXXXXXX
        dg --------
        dg XXXXXXXX
        dg --------
        dg --------

        ; 24 = "$" ╗
        dg --------
        dg --------
        dg --------
        dg XXXXX---
        dg ----X---
        dg XXX-X---
        dg --X-X---
        dg --X-X---

        ; 25 = "%" ║
        dg --X-X---
        dg --X-X---
        dg --X-X---
        dg --X-X---
        dg --X-X---
        dg --X-X---
        dg --X-X---
        dg --X-X---

        ; 26 = "&"
        dg --------
        dg -XX-XX--
        dg -XX-XX--
        dg --XXX---
        dg --XXX---
        dg -XX-XX--
        dg -XX-XX--
        dg --------


        ; 27 = "'" ╚
        dg --X-X---
        dg --X-XXXX
        dg --X-----
        dg --XXXXXX
        dg --------
        dg --------
        dg --------
        dg --------

        ; 28 = "(" ═
        dg --------
        dg XXXXXXXX
        dg --------
        dg XXXXXXXX
        dg --------
        dg --------
        dg --------
        dg --------

        ; 29 = ")" ╝
        dg --X-X---
        dg XXX-X---
        dg ----X---
        dg XXXXX---
        dg --------
        dg --------
        dg --------
        dg --------

        ; 2a = "*"
        dg --------
        dg --XXXXX-
        dg --XX----
        dg --XXXX--
        dg --XX----
        dg --XX----
        dg --XX----
        dg --------

        ; 2b = "+"
        dg XXX-----
        dg X-------
        dg XX---XX-
        dg X----X-X
        dg XXX--X-X
        dg -----X-X
        dg -----XX-
        dg --------

        ; 2c = ","
        dg --------
        dg --------
        dg --------
        dg --------
        dg --------
        dg ---XX---
        dg ---XX---
        dg --XX----

        ; 2d = "-"
        dg --------
        dg --------
        dg --------
        dg --------
        dg --------
        dg --------
        dg XXXXXXX-
        dg --------

        ; 2e = "."
        dg --------
        dg --------
        dg --------
        dg --------
        dg --------
        dg ---XX---
        dg ---XX---
        dg --------

        ; 2f = "/"
        dg XXXXXXXX
        dg --------
        dg --------
        dg --------
        dg --------
        dg --------
        dg --------
        dg --------

        ; 30 = "0"
        dg --XXX---
        dg -XX-XX--
        dg XX---XX-
        dg XX---XX-
        dg XX---XX-
        dg -XX-XX--
        dg --XXX---
        dg --------

        ; 31 = "1"
        dg ---XX---
        dg --XXX---
        dg ---XX---
        dg ---XX---
        dg ---XX---
        dg ---XX---
        dg -XXXXXX-
        dg --------

        ; 32 = "2"
        dg -XXXXX--
        dg XX---XX-
        dg -----XX-
        dg --XXXX--
        dg -XX-----
        dg XX------
        dg XXXXXXX-
        dg --------

        ; 33 = "3"
        dg XXXXXXX-
        dg ----XX--
        dg ---XX---
        dg --XXXX--
        dg -----XX-
        dg XX---XX-
        dg -XXXXX--
        dg --------

        ; 34 = "4"
        dg ---XXX--
        dg --XXXX--
        dg -XX-XX--
        dg XX--XX--
        dg XXXXXXX-
        dg ----XX--
        dg ----XX--
        dg --------

        ; 35 = "5"
        dg XXXXXXX-
        dg XX------
        dg XX------
        dg XXXXXX--
        dg -----XX-
        dg XX---XX-
        dg -XXXXX--
        dg --------

        ; 36 = "6"
        dg --XXXX--
        dg -XX-----
        dg XX------
        dg XXXXXX--
        dg XX---XX-
        dg XX---XX-
        dg -XXXXX--
        dg --------

        ; 37 = "7"
        dg XXXXXXX-
        dg XX---XX-
        dg ----XX--
        dg ---XX---
        dg --XX----
        dg --XX----
        dg --XX----
        dg --------

        ; 38 = "8"
        dg -XXXX---
        dg XX---X--
        dg XXX--X--
        dg -XXXX---
        dg X-XXXXX-
        dg X----XX-
        dg -XXXXX--
        dg --------

        ; 39 = "9"
        dg -XXXXX--
        dg XX---XX-
        dg XX---XX-
        dg -XXXXXX-
        dg -----XX-
        dg ----XX--
        dg -XXXX---
        dg --------

        ; 3a = ":"
        dg --------
        dg ---X-XX-
        dg --------
        dg ----X-XX
        dg --------
        dg ---X-XX-
        dg --------
        dg --------

        ; 3b = ";"
        dg --------
        dg XXXX----
        dg --------
        dg -XXXX---
        dg --------
        dg XXXX----
        dg --------
        dg --------

        ; 3c = "<"
        dg ---X----
        dg --XX----
        dg -XXXXXX-
        dg XXXXXXX-
        dg -XXXXXX-
        dg --XX----
        dg ---X----
        dg --------

        ; 3d = "="
        dg --------
        dg -------X
        dg -----XXX
        dg ----XX-X
        dg -----XXX
        dg -------X
        dg --------
        dg --------

        ; 3e = ">"
        dg --------
        dg XXXX----
        dg --------
        dg XXXX----
        dg --------
        dg XXXX----
        dg --------
        dg --------

        ; 3f = "?"
        dg ---X-XXX
        dg X---XXX-
        dg XXX-XX-X
        dg XXXXXXXX
        dg XXX-XX-X
        dg X---XXX-
        dg ---X-XXX
        dg --------

        ; 40 = "@"
        dg --------
        dg --XX----
        dg XXXXXX--
        dg XXXXXXXX
        dg XXXXXX--
        dg --XX----
        dg --------
        dg --------

        ; 41 = "A"
        dg --XXX---
        dg -XX-XX--
        dg XX---XX-
        dg XX---XX-
        dg XXXXXXX-
        dg XX---XX-
        dg XX---XX-
        dg --------

        ; 42 = "B"
        dg XXXXX---
        dg XX--XX--
        dg XX--XX--
        dg XXXXXX--
        dg XX---XX-
        dg XX---XX-
        dg XXXXXX--
        dg --------

        ; 43 = "C"
        dg --XXXX--
        dg -XX--XX-
        dg XX------
        dg XX------
        dg XX------
        dg -XX--XX-
        dg --XXXX--
        dg --------

        ; 44 = "D"
        dg XXXXX---
        dg XX--XX--
        dg XX---XX-
        dg XX---XX-
        dg XX---XX-
        dg XX--XX--
        dg XXXXX---
        dg --------

        ; 45 = "E"
        dg XXXXXXX-
        dg XX------
        dg XX------
        dg XXXXX---
        dg XX------
        dg XX------
        dg XXXXXXX-
        dg --------

        ; 46 = "F"
        dg XXXXXXX-
        dg XX------
        dg XX------
        dg XXXXX---
        dg XX------
        dg XX------
        dg XX------
        dg --------

        ; 47 = "G"
        dg --XXXX--
        dg -XX--XX-
        dg XX------
        dg XX--XXX-
        dg XX---XX-
        dg -XX--XX-
        dg --XXXXX-
        dg --------

        ; 48 = "H"
        dg XX---XX-
        dg XX---XX-
        dg XX---XX-
        dg XXXXXXX-
        dg XX---XX-
        dg XX---XX-
        dg XX---XX-
        dg --------

        ; 49 = "I"
        dg -XXXXXX-
        dg ---XX---
        dg ---XX---
        dg ---XX---
        dg ---XX---
        dg ---XX---
        dg -XXXXXX-
        dg --------

        ; 4a = "J"
        dg XXXXXXX-
        dg ----XX--
        dg ----XX--
        dg ----XX--
        dg ----XX--
        dg XX-XX---
        dg -XXX----
        dg --------

        ; 4b = "K"
        dg XX--XX--
        dg XX--XX--
        dg XX-XX---
        dg XXXX----
        dg XX-XX---
        dg XX--XX--
        dg XX---XX-
        dg --------

        ; 4c = "L"
        dg XX------
        dg XX------
        dg XX------
        dg XX------
        dg XX------
        dg XX------
        dg XXXXXXX-
        dg --------

        ; 4d = "M"
        dg XX---XX-
        dg XXX-XXX-
        dg XXXXXXX-
        dg XX-X-XX-
        dg XX---XX-
        dg XX---XX-
        dg XX---XX-
        dg --------

        ; 4e = "N"
        dg XX---XX-
        dg XXX--XX-
        dg XXXX-XX-
        dg XXXXXXX-
        dg XX-XXXX-
        dg XX--XXX-
        dg XX---XX-
        dg --------

        ; 4f = "O"
        dg -XXXXX--
        dg XX---XX-
        dg XX---XX-
        dg XX---XX-
        dg XX---XX-
        dg XX---XX-
        dg -XXXXX--
        dg --------

        ; 50 = "P"
        dg XXXXX---
        dg XX--XX--
        dg XX---XX-
        dg XX--XX--
        dg XXXXX---
        dg XX------
        dg XX------
        dg --------

        ; 51 = "Q"
        dg --XXX---
        dg -XX-XX--
        dg XX---XX-
        dg XX---XX-
        dg XX---XX-
        dg -XX-XX--
        dg --XXX-X-
        dg --------

        ; 52 = "R"
        dg XXXXX---
        dg XX--XX--
        dg XX---XX-
        dg XX--XX--
        dg XXXXX---
        dg XX--XX--
        dg XX---XX-
        dg --------

        ; 53 = "S"
        dg -XXXX---
        dg XX--XX--
        dg XX------
        dg -XXXXX--
        dg -----XX-
        dg XX---XX-
        dg -XXXXX--
        dg --------

        ; 54 = "T"
        dg -XXXXXX-
        dg ---XX---
        dg ---XX---
        dg ---XX---
        dg ---XX---
        dg ---XX---
        dg ---XX---
        dg --------

        ; 55 = "U"
        dg XX---XX-
        dg XX---XX-
        dg XX---XX-
        dg XX---XX-
        dg XX---XX-
        dg XX---XX-
        dg -XXXXX--
        dg --------

        ; 56 = "V"
        dg XX---XX-
        dg XX---XX-
        dg XX---XX-
        dg XX---XX-
        dg XX---XX-
        dg -XX-XX--
        dg --XXX---
        dg --------

        ; 57 = "W"
        dg XX---XX-
        dg XX---XX-
        dg XX---XX-
        dg XX-X-XX-
        dg XXXXXXX-
        dg XXX-XXX-
        dg XX---XX-
        dg --------

        ; 58 = "X"
        dg XX---XX-
        dg XXX-XXX-
        dg -XXXXX--
        dg --XXX---
        dg -XXXXX--
        dg XXX-XXX-
        dg XX---XX-
        dg --------

        ; 59 = "Y"
        dg XX---XX-
        dg XX---XX-
        dg XX---XX-
        dg -XXXXX--
        dg --XXX---
        dg --XXX---
        dg --XXX---
        dg --------

        ; 5a = "Z"
        dg XXXXXXX-
        dg ----XX--
        dg ---XX---
        dg --XX----
        dg -XX-----
        dg XX------
        dg XXXXXXX-
        dg --------

        ; 5b
        dg XXX-----
        dg XXX-XX-X
        dg XXX-XX-X
        dg XXX-XX-X
        dg XXX-XX-X
        dg XXX-XX-X
        dg XXX-----
        dg --------

        ; 5c
        dg XX-XXX--
        dg XXX-XXX-
        dg -XX-----
        dg X-X-XXX-
        dg X-X-----
        dg XX--XXX-
        dg XXXXXX--
        dg --------

        ; 5d
        dg --------
        dg --------
        dg ---X-XXX
        dg ---X-XXX
        dg ---X-XXX
        dg --------
        dg --------
        dg --------

        ; 5e
        dg --------
        dg --------
        dg XXXXX---
        dg XXXX----
        dg XXX-----
        dg --------
        dg --------
        dg --------

        ; 5f
        dg --------
        dg --------
        dg ------XX
        dg ---XXXXX
        dg ------XX
        dg --------
        dg --------
        dg --------

        ; 60
        dg --------
        dg XXXXX---
        dg XXXXXX--
        dg XXXXXX--
        dg XXXXXX--
        dg XXXXX---
        dg --------
        dg --------

        ; 61
        dg --------
        dg -------X
        dg ------X-
        dg ----XXXX
        dg ------X-
        dg -------X
        dg --------
        dg --------

        ; 62
        dg --------
        dg --------
        dg XX------
        dg -XXXX---
        dg XX------
        dg --------
        dg --------
        dg --------

        ; 63
        dg ------X-
        dg -------X
        dg -------X
        dg ------XX
        dg -----X-X
        dg ----X---
        dg --------
        dg --------

        ; 64
        dg --------
        dg --------
        dg X--X----
        dg XXX-----
        dg XX------
        dg X-------
        dg X-------
        dg -X------

        ; 65
        dg ------XX
        dg ------XX
        dg ------XX
        dg ------X-
        dg ------X-
        dg ----XXX-
        dg ---XXXX-
        dg ----XX--

        ; 66
        dg XXXX----
        dg XXXX----
        dg XXXX----
        dg ---X----
        dg ---X----
        dg -XXX----
        dg XXXX----
        dg -XX-----

        ; 67
        dg --------
        dg ------X-
        dg -----XX-
        dg -----XXX
        dg -----XX-
        dg ------X-
        dg --------
        dg --------

        ; 68
        dg --------
        dg --X-----
        dg -XX-X-X-
        dg -XXXXXXX
        dg -XX-X-X-
        dg --X-----
        dg --------
        dg --------

        ; 69
        dg -----XXX
        dg --X-----
        dg -XX-X-X-
        dg -XXXXXXX
        dg -XX-X-X-
        dg --X-----
        dg -----XXX
        dg --------

        ; 6a
        dg ------XX
        dg ------XX
        dg X-X-XXX-
        dg XXXXXXX-
        dg X-X-XXX-
        dg ------XX
        dg ------XX
        dg --------

        ; 6b
        dg ------XX
        dg ------XX
        dg X-X-X-X-
        dg XXXXXXX-
        dg X-X-X-X-
        dg ------XX
        dg ------XX
        dg --------

        ; 6c
        dg -XXXX---
        dg XX------
        dg XX-X-X-X
        dg XX--X-X-
        dg XX-X-X-X
        dg XX------
        dg -XXXX---
        dg --------

        ; 6d
        dg X-------
        dg --------
        dg -X-X-X-X
        dg X-X-X-XX
        dg -X-X-X-X
        dg --------
        dg X-------
        dg --------

        ; 6e
        dg --XX-XXX
        dg --XXXX--
        dg X-X-XX-X
        dg XXXXXX--
        dg X-X-XX-X
        dg --XXXX--
        dg --XX-XXX
        dg --------

        ; 6f
        dg X-------
        dg --------
        dg -X-X-XXX
        dg X-X-XXXX
        dg -X-X-XXX
        dg --------
        dg X-------
        dg --------

        ; 70
        dg X-XX-XXX
        dg -XXXXX--
        dg XXX-XX-X
        dg XXXXXX--
        dg XXX-XX-X
        dg -XXXXX--
        dg X-XX-XXX
        dg --------

        ; 71
        dg X-------
        dg --------
        dg -XXXXXXX
        dg XXXXXXXX
        dg -XXXXXXX
        dg --------
        dg X-------
        dg --------

        ; 72
        dg XX------
        dg --------
        dg XXXXXXXX
        dg XXXXXXXX
        dg XXXXXXXX
        dg --------
        dg XX------
        dg --------

        ; 73
        dg XX------
        dg ---XX---
        dg XXXXXXXX
        dg XXXXXXXX
        dg XXXXXXXX
        dg ---XX---
        dg XX------
        dg --------

        ; 74
        dg X-XX-XXX
        dg -XXXXX--
        dg XXX-XXXX
        dg XXXXXXXX
        dg XXX-XXXX
        dg -XXXXX--
        dg X-XX-XXX
        dg --------

        ; 75
        dg XX--X---
        dg ---XXX--
        dg XXXXXXXX
        dg XXXXXXXX
        dg XXXXXXXX
        dg ---XXX--
        dg XX--X---
        dg --------

        ; 76
        dg XX--X---
        dg ---XXXXX
        dg XXXXXXXX
        dg XXXXXXXX
        dg XXXXXXXX
        dg ---XXXXX
        dg XX--X---
        dg --------

        ; 77
        dg XX-XXX--
        dg --XXXXXX
        dg XXXXXXXX
        dg XXXXXXXX
        dg XXXXXXXX
        dg --XXXXXX
        dg XX-XXX--
        dg --------

        ; 78
        dg XX-XXXXX
        dg --XXXXXX
        dg XXXXXXXX
        dg XXXXXXXX
        dg XXXXXXXX
        dg --XXXXXX
        dg XX-XXXXX
        dg --------

        ; 79
        dg --------
        dg --------
        dg -X-X-X-X
        dg X-X-X-X-
        dg -X-X-X-X
        dg --------
        dg --------
        dg --------

        ; 7a
        dg --------
        dg --------
        dg -X-XXX-X
        dg X-XXXXX-
        dg -X-XXX-X
        dg --------
        dg --------
        dg --------

        ; 7b
        dg --------
        dg --------
        dg -X-XXXXX
        dg X-XXXXXX
        dg -X-XXXXX
        dg --------
        dg --------
        dg --------

        ; 7c
        dg --------
        dg --------
        dg XXXXXX-X
        dg XXXXXXX-
        dg XXXXXX-X
        dg --------
        dg --------
        dg --------

        ; 7d
        dg --------
        dg --------
        dg XXXXXXXX
        dg XXXXXXXX
        dg XXXXXXXX
        dg --------
        dg --------
        dg --------

        ; 7e
        dg --------
        dg ----X--X
        dg XXXXXXXX
        dg XXXXXXXX
        dg XXXXXXXX
        dg ----X--X
        dg --------
        dg --------

        ; 7f
        dg ----X---
        dg --XXXX-X
        dg XXXXXXXX
        dg XXXXXXXX
        dg XXXXXXXX
        dg --XXXX-X
        dg ----X---
        dg --------

        ; 80
        dg ----X---
        dg --XXXXXX
        dg XXXXXXXX
        dg XXXXXXXX
        dg XXXXXXXX
        dg --XXXXXX
        dg ----X---
        dg --------

        ; 81
        dg --XXXX--
        dg XXXXXXXX
        dg XXXXXXXX
        dg XXXXXXXX
        dg XXXXXXXX
        dg XXXXXXXX
        dg --XXXX--
        dg --------

        ; 82
        dg --------
        dg XX------
        dg XXXXXXXX
        dg XXXXXXXX
        dg XXXXXXXX
        dg XX------
        dg --------
        dg --------

        ; 83
        dg --------
        dg --------
        dg -X------
        dg X-X-X-X-
        dg -X------
        dg --------
        dg --------
        dg --------

        ; 84
        dg --------
        dg --------
        dg XXX-----
        dg XXXXXXX-
        dg XXX-----
        dg --------
        dg --------
        dg --------

        ; 85
        dg --------
        dg --------
        dg --------
        dg --------
        dg --------
        dg --------
        dg --------
        dg --------

        ; 86
        dg --------
        dg --------
        dg --------
        dg --------
        dg --------
        dg --------
        dg --------
        dg --------

