; 
                org 0x7600

Logo_ani_pt1
                dw 0x9e34
                db 0x13
                db 0x07, 0x00, 0xfc
                db 0

                dw 0x9e28
                db 0x11
                db 0x06, 0x00, 0xfc
                db 0

                dw 0x16e8
                db 0x0f
                db 0x07, 0x08, 0x00
                db 0

                dw 0x2a98
                db 0x12
                db 0x0f, 0xf8, 0x00
                db 0

                dw 0x1c98
                db 0x0f
                db 0x0f, 0xf8, 0x00
                db 1

                dw 0xf230
                db 0x13
                db 0x14, 0x00, 0x04
                db 0

                dw 0x36e8
                db 0x11
                db 0x08, 0x08, 0x00
                db 0

                dw 0x3698
                db 0x15
                db 0x0f, 0xf8, 0x00
                db 0
                
                dw 0x9e40
                db 0x13
                db 0x10, 0x00, 0xfc
                db 0

                dw 0x56ec
                db 0x0d
                db 0x0f, 0x04, 0
                db 0

                dw 0xf234
                db 0x14
                db 0x18, 0x00, 0x04
                db 1

                dw 0x9e28
                db 0x14
                db 0x13, 0x00, 0xfc
                db 0

                dw 0x7aec
                db 0x0d
                db 0x0f, 0x04, 0x00
                db 1


                dw 0x6ea4
                db 0x10
                db 0x0e, 0xf8, 0x00
                db 0

                dw 0x9e28
                db 0x17
                db 0x0d, 0x00, 0xfc
                db 0

Logo_ani_pt2

                dw 0x62ec
                db 0x0e
                db 0x0d, 0x04, 0x00
                db 0

                dw 0x4aec
                db 0x0c
                db 0x0f, 0x04, 0x00
                db 0

                dw 0x26ec
                db 0x0d
                db 0x0d, 0x04, 0x00
                db 0

                dw 0xf2a6
                db 0x0b
                db 0x15, 0xff, 0x04
                db 0

                dw 0xf228
                db 0x11
                db 0x06, 0x00, 0x04
                db 1

                dw 0x0e28
                db 0x16
                db 0x03, 0x00, 0x02
                db 0

                dw 0x1328
                db 0x16
                db 0x04, 0x00, 0x02
                db 0

                dw 0x1828
                db 0x16
                db 0x04, 0x00, 0x02
                db 0

                dw 0x1d28
                db 0x16
                db 0x04, 0x00, 0x02
                db 0

                dw 0x2228
                db 0x16
                db 0x04, 0x00, 0x02
                db 0

                dw 0x2728
                db 0x16
                db 0x04, 0x00, 0x02
                db 0

